SET local check_function_bodies = off;

CREATE SEQUENCE "public"."ledger_entries_id_seq" AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 NO CYCLE;

CREATE TABLE "public"."anchor_types" (
  "anchor_id"  bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "type_name"  character varying        NOT NULL,
  "vector"     real[]                   NOT NULL,
  "axis"       character varying        NOT NULL,
  CONSTRAINT "anchor_types_pkey" PRIMARY KEY (anchor_id),
  CONSTRAINT "anchor_types_type_name_key" UNIQUE (type_name)
);

ALTER TABLE "public"."anchor_types"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."content_who_are_they" (
  "prompt_id" uuid    NOT NULL,
  "axis"      text    NOT NULL,
  "content"   text    NOT NULL,
  "anchor"    boolean DEFAULT false,
  "detail"    text,
  CONSTRAINT "content_pkey" PRIMARY KEY (prompt_id),
  CONSTRAINT "content_prompt_id_key" UNIQUE (prompt_id)
);

CREATE TABLE "public"."drinking_statuses" (
  "code" text NOT NULL,
  CONSTRAINT "drinking_statuses_pkey" PRIMARY KEY (code)
);

CREATE TABLE "public"."embedded_content_who_are_they" (
  "prompt_id" uuid    NOT NULL,
  "axis"      text    NOT NULL,
  "weight"    real    NOT NULL,
  "embedding" real[]  NOT NULL,
  "anchor"    boolean NOT NULL,
  CONSTRAINT "prompts_id_key" UNIQUE (prompt_id),
  CONSTRAINT "prompts_pkey" PRIMARY KEY (prompt_id)
);

ALTER TABLE "public"."embedded_content_who_are_they"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."genders" (
  "code" text NOT NULL,
  CONSTRAINT "genders_pkey" PRIMARY KEY (code)
);

CREATE TABLE "public"."hard_gated_candidates" (
  "user_id"           uuid                     NOT NULL,
  "candidate_user_id" uuid                     NOT NULL,
  "generated_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "expires_at"        timestamp with time zone,
  "updated_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "distance_km"       double precision,
  "hard_gate_version" integer                  NOT NULL DEFAULT 1,
  "consumed"          boolean                  NOT NULL DEFAULT false,
  "consumed_at"       timestamp with time zone,
  CONSTRAINT "gated_matches_check" CHECK ((user_id <> candidate_user_id)),
  CONSTRAINT "gated_matches_pkey" PRIMARY KEY (user_id, candidate_user_id)
);

CREATE TABLE "public"."interested_pair_question_answers" (
  "answer_id"           uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_low_id"         uuid                     NOT NULL,
  "user_high_id"        uuid                     NOT NULL,
  "question_id"         uuid                     NOT NULL,
  "asked_by_user_id"    uuid                     NOT NULL,
  "answered_by_user_id" uuid                     NOT NULL,
  "answer"              text                     NOT NULL,
  "created_at"          timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"          timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "interested_pair_question_answers_answer_not_empty" CHECK ((length(TRIM(BOTH FROM answer)) > 0)),
  CONSTRAINT "interested_pair_question_answers_different_users_check" CHECK ((asked_by_user_id <> answered_by_user_id)),
  CONSTRAINT "interested_pair_question_answers_one_answer_per_question" UNIQUE (user_low_id, user_high_id, question_id),
  CONSTRAINT "interested_pair_question_answers_pair_order_check" CHECK ((user_low_id < user_high_id)),
  CONSTRAINT "interested_pair_question_answers_pkey" PRIMARY KEY (answer_id),
  CONSTRAINT "interested_pair_question_answers_users_match_pair_check"
    CHECK (((LEAST(asked_by_user_id, answered_by_user_id) = user_low_id) AND (GREATEST(asked_by_user_id, answered_by_user_id) = user_high_id)))
);

ALTER TABLE "public"."interested_pair_question_answers"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."interested_pairs" (
  "user_low_id"                uuid                     NOT NULL,
  "user_high_id"               uuid                     NOT NULL,
  "low_questions_answered_at"  timestamp with time zone,
  "high_questions_answered_at" timestamp with time zone,
  "low_final_decision"         text,
  "high_final_decision"        text,
  "state"                      text                     NOT NULL DEFAULT 'awaiting_both_answers'::text,
  "created_at"                 timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"                 timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "interested_pairs_high_final_decision_check" CHECK (((high_final_decision IS NULL) OR (high_final_decision = ANY (ARRAY['yes'::text, 'no'::text])))),
  CONSTRAINT "interested_pairs_low_final_decision_check" CHECK (((low_final_decision IS NULL) OR (low_final_decision = ANY (ARRAY['yes'::text, 'no'::text])))),
  CONSTRAINT "interested_pairs_pkey" PRIMARY KEY (user_low_id, user_high_id),
  CONSTRAINT "interested_pairs_state_check"
    CHECK
    ((state = ANY (ARRAY['awaiting_both_answers'::text, 'awaiting_low_answers'::text, 'awaiting_high_answers'::text, 'awaiting_both_final_decisions'::text,
    'awaiting_low_final_decision'::text, 'awaiting_high_final_decision'::text, 'confirmed'::text, 'rejected'::text, 'expired'::text]))),
  CONSTRAINT "interested_pairs_user_order_check" CHECK ((user_low_id < user_high_id))
);

ALTER TABLE "public"."interested_pairs"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."kids_preferences" (
  "code" text NOT NULL,
  CONSTRAINT "kids_preferences_pkey" PRIMARY KEY (code)
);

CREATE TABLE "public"."ledger_entries" (
  "id"         bigint                   NOT NULL DEFAULT nextval('public.ledger_entries_id_seq'::regclass),
  "user_id"    uuid                     NOT NULL,
  "prompt_id"  uuid                     NOT NULL,
  "reaction"   smallint                 NOT NULL,
  "embedding"  real[],
  "weight"     real                     NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "axis"       text,
  "anchor"     boolean                  NOT NULL,
  CONSTRAINT "ledger_entries_pkey" PRIMARY KEY (id),
  CONSTRAINT "ledger_user_prompt_unique" UNIQUE (user_id, prompt_id)
);

CREATE TABLE "public"."match_queue" (
  "id"                uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"           uuid                     NOT NULL,
  "candidate_user_id" uuid                     NOT NULL,
  "position"          integer                  NOT NULL,
  "status"            text                     NOT NULL DEFAULT 'queued'::text,
  "score"             numeric(8,5),
  "released_at"       timestamp with time zone,
  "consumed_at"       timestamp with time zone,
  "expires_at"        timestamp with time zone,
  "created_at"        timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "match_queue_check" CHECK ((user_id <> candidate_user_id)),
  CONSTRAINT "match_queue_pkey" PRIMARY KEY (id),
  CONSTRAINT "match_queue_position_check" CHECK (("position" >= 0)),
  CONSTRAINT "match_queue_status_check" CHECK ((status = ANY (ARRAY['queued'::text, 'visible'::text, 'consumed'::text, 'expired'::text, 'removed'::text]))),
  CONSTRAINT "match_queue_user_id_candidate_user_id_key" UNIQUE (user_id, candidate_user_id)
);

CREATE TABLE "public"."matches" (
  "user_low_id"    uuid                     NOT NULL,
  "user_high_id"   uuid                     NOT NULL,
  "matched_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "chat_thread_id" uuid,
  "unmatched_at"   timestamp with time zone,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "matches_check1" CHECK ((user_low_id < user_high_id)),
  CONSTRAINT "matches_check" CHECK ((user_low_id <> user_high_id)),
  CONSTRAINT "matches_pkey" PRIMARY KEY (user_low_id, user_high_id)
);

CREATE TABLE "public"."pair_state" (
  "user_low_id"     uuid                     NOT NULL,
  "user_high_id"    uuid                     NOT NULL,
  "low_seen_at"     timestamp with time zone,
  "high_seen_at"    timestamp with time zone,
  "low_decision"    text,
  "high_decision"   text,
  "low_decided_at"  timestamp with time zone,
  "high_decided_at" timestamp with time zone,
  "state"           text                     NOT NULL DEFAULT 'unseen'::text,
  "matched_at"      timestamp with time zone,
  "created_at"      timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "pair_state_check1" CHECK ((user_low_id < user_high_id)),
  CONSTRAINT "pair_state_check2" CHECK ((((low_decision IS NULL) AND (low_decided_at IS NULL)) OR ((low_decision IS NOT NULL) AND (low_decided_at IS NOT NULL)))),
  CONSTRAINT "pair_state_check3" CHECK ((((high_decision IS NULL) AND (high_decided_at IS NULL)) OR ((high_decision IS NOT NULL) AND (high_decided_at IS NOT NULL)))),
  CONSTRAINT "pair_state_check4" CHECK ((((state = 'matched'::text) AND (matched_at IS NOT NULL)) OR ((state <> 'matched'::text) AND (matched_at IS NULL)))),
  CONSTRAINT "pair_state_check" CHECK ((user_low_id <> user_high_id)),
  CONSTRAINT "pair_state_high_decision_check" CHECK ((high_decision = ANY (ARRAY['like'::text, 'pass'::text, 'block'::text]))),
  CONSTRAINT "pair_state_low_decision_check" CHECK ((low_decision = ANY (ARRAY['like'::text, 'pass'::text, 'block'::text]))),
  CONSTRAINT "pair_state_pkey" PRIMARY KEY (user_low_id, user_high_id),
  CONSTRAINT "pair_state_state_check"
    CHECK ((state = ANY (ARRAY['unseen'::text, 'pending_low_like'::text, 'pending_high_like'::text, 'matched'::text, 'rejected'::text, 'blocked'::text])))
);

CREATE TABLE "public"."relationship_intents" (
  "code" text NOT NULL,
  CONSTRAINT "relationship_intents_pkey" PRIMARY KEY (code)
);

CREATE TABLE "public"."religions" (
  "code" text NOT NULL,
  CONSTRAINT "religions_pkey" PRIMARY KEY (code)
);

CREATE TABLE "public"."serious_candidates" (
  "user_id"           uuid                     NOT NULL,
  "candidate_user_id" uuid                     NOT NULL,
  "position"          integer                  NOT NULL,
  "score"             numeric(8,5)             NOT NULL,
  "status"            text                     NOT NULL DEFAULT 'available'::text,
  "released_at"       timestamp with time zone,
  "expires_at"        timestamp with time zone,
  "created_at"        timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "serious_candidates_check" CHECK ((user_id <> candidate_user_id)),
  CONSTRAINT "serious_candidates_pkey" PRIMARY KEY (user_id, candidate_user_id),
  CONSTRAINT "serious_candidates_position_check" CHECK (("position" >= 0)),
  CONSTRAINT "serious_candidates_status_check" CHECK ((status = ANY (ARRAY['available'::text, 'released'::text, 'expired'::text, 'removed'::text])))
);

CREATE TABLE "public"."smoking_statuses" (
  "code" text NOT NULL,
  CONSTRAINT "smoking_statuses_pkey" PRIMARY KEY (code)
);

CREATE TABLE "public"."user_computed" (
  "user_id"                       uuid                     NOT NULL,
  "computed_at"                   timestamp with time zone NOT NULL DEFAULT now(),
  "attachment_closeness_type"     text,
  "attachment_closeness_margin"   real,
  "attachment_reassurance_type"   text,
  "attachment_reassurance_margin" real,
  "summary"                       text,
  CONSTRAINT "user_computed_pkey" PRIMARY KEY (user_id)
);

ALTER TABLE "public"."user_computed"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_info_vectors" (
  "user_id"           uuid                     NOT NULL,
  "profile_vector"    real[],
  "preference_vector" real[],
  "created_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "axis"              text                     NOT NULL,
  "vector"            real[],
  CONSTRAINT "user_info_vectors_pkey" PRIMARY KEY (user_id, axis)
);

CREATE TABLE "public"."user_match_questions" (
  "question_id" uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"     uuid                     NOT NULL,
  "question"    text                     NOT NULL,
  "position"    integer                  NOT NULL DEFAULT 0,
  "is_required" boolean                  NOT NULL DEFAULT true,
  "is_active"   boolean                  NOT NULL DEFAULT true,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"  timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_match_questions_pkey" PRIMARY KEY (question_id),
  CONSTRAINT "user_match_questions_position_check" CHECK (("position" >= 0)),
  CONSTRAINT "user_match_questions_question_not_empty" CHECK ((length(TRIM(BOTH FROM question)) > 0)),
  CONSTRAINT "user_match_questions_question_user_unique" UNIQUE (question_id, user_id)
);

ALTER TABLE "public"."user_match_questions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user_photos" (
  "id"           uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "user_id"      uuid                     NOT NULL,
  "storage_path" text                     NOT NULL,
  "position"     smallint                 NOT NULL,
  "is_primary"   boolean                  NOT NULL DEFAULT false,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_photos_pkey" PRIMARY KEY (id),
  CONSTRAINT "user_photos_position_check" CHECK (("position" >= 0))
);

CREATE TABLE "public"."user_preferences" (
  "user_id"               uuid                     NOT NULL,
  "min_age"               smallint,
  "max_age"               smallint,
  "min_height_cm"         smallint,
  "max_height_cm"         smallint,
  "max_distance_km"       integer,
  "exclude_smokers"       boolean                  NOT NULL DEFAULT false,
  "require_same_religion" boolean                  NOT NULL DEFAULT false,
  "created_at"            timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"            timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_preferences_check1" CHECK (((min_height_cm IS NULL) OR (max_height_cm IS NULL) OR (min_height_cm <= max_height_cm))),
  CONSTRAINT "user_preferences_check" CHECK (((min_age IS NULL) OR (max_age IS NULL) OR (min_age <= max_age))),
  CONSTRAINT "user_preferences_max_age_check" CHECK (((max_age IS NULL) OR ((max_age >= 18) AND (max_age <= 100)))),
  CONSTRAINT "user_preferences_max_distance_km_check" CHECK (((max_distance_km IS NULL) OR (max_distance_km >= 0))),
  CONSTRAINT "user_preferences_max_height_cm_check" CHECK (((max_height_cm IS NULL) OR ((max_height_cm >= 100) AND (max_height_cm <= 250)))),
  CONSTRAINT "user_preferences_min_age_check" CHECK (((min_age IS NULL) OR ((min_age >= 18) AND (min_age <= 100)))),
  CONSTRAINT "user_preferences_min_height_cm_check" CHECK (((min_height_cm IS NULL) OR ((min_height_cm >= 100) AND (min_height_cm <= 250)))),
  CONSTRAINT "user_preferences_pkey" PRIMARY KEY (user_id)
);

CREATE TABLE "public"."user_preferred_genders" (
  "user_id"     uuid NOT NULL,
  "gender_code" text NOT NULL,
  CONSTRAINT "user_preferred_genders_pkey" PRIMARY KEY (user_id, gender_code)
);

CREATE TABLE "public"."user_preferred_relationship_intents" (
  "user_id"     uuid NOT NULL,
  "intent_code" text NOT NULL,
  CONSTRAINT "user_preferred_relationship_intents_pkey" PRIMARY KEY (user_id, intent_code)
);

CREATE TABLE "public"."user_preferred_religions" (
  "user_id"       uuid NOT NULL,
  "religion_code" text NOT NULL,
  CONSTRAINT "user_preferred_religions_pkey" PRIMARY KEY (user_id, religion_code)
);

CREATE TABLE "public"."user_profile" (
  "user_id"                  uuid                     NOT NULL,
  "date_of_birth"            date                     NOT NULL,
  "height_cm"                smallint,
  "gender_code"              text                     NOT NULL,
  "religion_code"            text,
  "relationship_intent_code" text,
  "wants_kids_code"          text,
  "smoking_status_code"      text,
  "drinking_status_code"     text,
  "city"                     text,
  "country"                  text,
  "latitude"                 double precision,
  "longitude"                double precision,
  "bio"                      text,
  "created_at"               timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"               timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "user_profile_height_cm_check" CHECK (((height_cm IS NULL) OR ((height_cm >= 100) AND (height_cm <= 250)))),
  CONSTRAINT "user_profile_pkey" PRIMARY KEY (user_id)
);

CREATE TABLE "public"."users" (
  "id"            uuid                     NOT NULL,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "display_name"  text,
  "birth_date"    date,
  "location_text" text,
  "is_active"     boolean                  NOT NULL DEFAULT true,
  "is_banned"     boolean                  NOT NULL DEFAULT false,
  "last_seen_at"  timestamp with time zone,
  CONSTRAINT "users_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."users"
  ENABLE ROW LEVEL SECURITY;

ALTER SEQUENCE "public"."ledger_entries_id_seq" OWNED BY "public"."ledger_entries"."id";

CREATE OR REPLACE FUNCTION public.distance_km (
  lat1 double precision,
  lon1 double precision,
  lat2 double precision,
  lon2 double precision
)
  RETURNS double precision
  LANGUAGE sql
  IMMUTABLE
  AS $function$
    select case
        when lat1 is null or lon1 is null or lat2 is null or lon2 is null then null
        else
            6371.0 * acos(
                least(
                    1.0,
                    cos(radians(lat1)) * cos(radians(lat2)) * cos(radians(lon2) - radians(lon1))
                    + sin(radians(lat1)) * sin(radians(lat2))
                )
            )
    end
$function$;

CREATE OR REPLACE FUNCTION public.refill_gated_matches_for_user (
  p_user_id uuid,
  p_limit   integer DEFAULT 50
)
  RETURNS integer
  LANGUAGE plpgsql
  AS $function$
declare
    v_inserted_count integer := 0;
begin
    with me as (
        select
            up.user_id,
            up.date_of_birth,
            date_part('year', age(current_date, up.date_of_birth))::int as age_years,
            up.height_cm,
            up.gender_code,
            up.religion_code,
            up.relationship_intent_code,
            up.smoking_status_code,
            up.latitude,
            up.longitude,
            pref.min_age,
            pref.max_age,
            pref.min_height_cm,
            pref.max_height_cm,
            pref.max_distance_km,
            pref.exclude_smokers,
            pref.require_same_religion
        from public.user_profile up
        join public.user_preferences pref
          on pref.user_id = up.user_id
        where up.user_id = p_user_id
    ),
    candidate_pool as (
        select
            cand.user_id as candidate_user_id,
            cand.date_of_birth,
            date_part('year', age(current_date, cand.date_of_birth))::int as candidate_age_years,
            cand.height_cm,
            cand.gender_code,
            cand.religion_code,
            cand.relationship_intent_code,
            cand.smoking_status_code,
            cand.latitude,
            cand.longitude,
            cand_pref.min_age as cand_min_age,
            cand_pref.max_age as cand_max_age,
            cand_pref.min_height_cm as cand_min_height_cm,
            cand_pref.max_height_cm as cand_max_height_cm,
            cand_pref.max_distance_km as cand_max_distance_km,
            cand_pref.exclude_smokers as cand_exclude_smokers,
            cand_pref.require_same_religion as cand_require_same_religion
        from public.user_profile cand
        join public.user_preferences cand_pref
          on cand_pref.user_id = cand.user_id
        where cand.user_id <> p_user_id
    ),
    filtered_candidates as (
        select
            cp.candidate_user_id,
            public.distance_km(me.latitude, me.longitude, cp.latitude, cp.longitude) as computed_distance_km
        from candidate_pool cp
        cross join me
        where
            -- changed: only block if already present and still unconsumed
            not exists (
                select 1
                from public.hard_gated_candidates gm
                where gm.user_id = p_user_id
                  and gm.candidate_user_id = cp.candidate_user_id
                  and gm.consumed = false
            )
            and not exists (
                select 1
                from public.match_queue mq
                where mq.user_id = p_user_id
                  and mq.candidate_user_id = cp.candidate_user_id
                  and mq.status in ('queued', 'visible')
            )
            and not exists (
                select 1
                from public.matches m
                where m.user_low_id = least(p_user_id, cp.candidate_user_id)
                  and m.user_high_id = greatest(p_user_id, cp.candidate_user_id)
            )
            and not exists (
                select 1
                from public.pair_state ps
                where ps.user_low_id = least(p_user_id, cp.candidate_user_id)
                  and ps.user_high_id = greatest(p_user_id, cp.candidate_user_id)
            )
            and exists (
                select 1
                from public.user_preferred_genders my_pg
                where my_pg.user_id = p_user_id
                  and my_pg.gender_code = cp.gender_code
            )
            and exists (
                select 1
                from public.user_preferred_genders cand_pg
                where cand_pg.user_id = cp.candidate_user_id
                  and cand_pg.gender_code = me.gender_code
            )
            and cp.candidate_age_years between coalesce(me.min_age, 18) and coalesce(me.max_age, 100)
            and me.age_years between coalesce(cp.cand_min_age, 18) and coalesce(cp.cand_max_age, 100)
            and (
                me.min_height_cm is null
                or cp.height_cm is null
                or cp.height_cm >= me.min_height_cm
            )
            and (
                me.max_height_cm is null
                or cp.height_cm is null
                or cp.height_cm <= me.max_height_cm
            )
            and (
                cp.cand_min_height_cm is null
                or me.height_cm is null
                or me.height_cm >= cp.cand_min_height_cm
            )
            and (
                cp.cand_max_height_cm is null
                or me.height_cm is null
                or me.height_cm <= cp.cand_max_height_cm
            )
            and (
                me.exclude_smokers = false
                or cp.smoking_status_code is distinct from 'smoker'
            )
            and (
                cp.cand_exclude_smokers = false
                or me.smoking_status_code is distinct from 'smoker'
            )
            and (
                me.require_same_religion = false
                or (
                    me.religion_code is not null
                    and cp.religion_code is not null
                    and me.religion_code = cp.religion_code
                )
            )
            and (
                cp.cand_require_same_religion = false
                or (
                    me.religion_code is not null
                    and cp.religion_code is not null
                    and me.religion_code = cp.religion_code
                )
            )
            and (
                not exists (
                    select 1
                    from public.user_preferred_religions upr
                    where upr.user_id = p_user_id
                )
                or exists (
                    select 1
                    from public.user_preferred_religions upr
                    where upr.user_id = p_user_id
                      and upr.religion_code = cp.religion_code
                )
            )
            and (
                not exists (
                    select 1
                    from public.user_preferred_religions upr
                    where upr.user_id = cp.candidate_user_id
                )
                or exists (
                    select 1
                    from public.user_preferred_religions upr
                    where upr.user_id = cp.candidate_user_id
                      and upr.religion_code = me.religion_code
                )
            )

            -- changed: intent filter allows either direct intent match OR overlap in preference sets
            and (
                not exists (
                    select 1
                    from public.user_preferred_relationship_intents upi
                    where upi.user_id = p_user_id
                )
                or cp.relationship_intent_code is null
                or exists (
                    select 1
                    from public.user_preferred_relationship_intents upi
                    where upi.user_id = p_user_id
                      and upi.intent_code = cp.relationship_intent_code
                )
                or exists (
                    select 1
                    from public.user_preferred_relationship_intents mine
                    join public.user_preferred_relationship_intents theirs
                      on theirs.user_id = cp.candidate_user_id
                     and theirs.intent_code = mine.intent_code
                    where mine.user_id = p_user_id
                )
            )
            and (
                not exists (
                    select 1
                    from public.user_preferred_relationship_intents upi
                    where upi.user_id = cp.candidate_user_id
                )
                or me.relationship_intent_code is null
                or exists (
                    select 1
                    from public.user_preferred_relationship_intents upi
                    where upi.user_id = cp.candidate_user_id
                      and upi.intent_code = me.relationship_intent_code
                )
                or exists (
                    select 1
                    from public.user_preferred_relationship_intents mine
                    join public.user_preferred_relationship_intents theirs
                      on theirs.user_id = p_user_id
                     and theirs.intent_code = mine.intent_code
                    where mine.user_id = cp.candidate_user_id
                )
            )

            and (
                me.max_distance_km is null
                or public.distance_km(me.latitude, me.longitude, cp.latitude, cp.longitude) is null
                or public.distance_km(me.latitude, me.longitude, cp.latitude, cp.longitude) <= me.max_distance_km
            )
            and (
                cp.cand_max_distance_km is null
                or public.distance_km(me.latitude, me.longitude, cp.latitude, cp.longitude) is null
                or public.distance_km(me.latitude, me.longitude, cp.latitude, cp.longitude) <= cp.cand_max_distance_km
            )
        order by random()
        limit p_limit
    ),
    inserted as (
        insert into public.hard_gated_candidates (
            user_id,
            candidate_user_id,
            generated_at,
            distance_km,
            hard_gate_version,
            consumed
        )
        select
            p_user_id,
            fc.candidate_user_id,
            now(),
            fc.computed_distance_km,
            2,
            false
        from filtered_candidates fc
        on conflict (user_id, candidate_user_id) do nothing
        returning 1
    )
    select count(*) into v_inserted_count
    from inserted;

    return v_inserted_count;
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_interested_pair_question_answers_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_interested_pairs_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
begin
    new.updated_at = now();
    return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.set_user_match_questions_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$;

ALTER TABLE "public"."embedded_content_who_are_they"
  ADD CONSTRAINT "prompts_prompt_id_fkey" FOREIGN KEY (prompt_id) REFERENCES public.content_who_are_they(prompt_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."hard_gated_candidates"
  ADD CONSTRAINT "gated_matches_candidate_user_id_fkey" FOREIGN KEY (candidate_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."hard_gated_candidates"
  ADD CONSTRAINT "gated_matches_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."interested_pair_question_answers"
  ADD CONSTRAINT "interested_pair_question_answers_pair_fk" FOREIGN KEY (user_low_id, user_high_id) REFERENCES public.interested_pairs(user_low_id, user_high_id) ON DELETE CASCADE;

ALTER TABLE "public"."ledger_entries"
  ADD CONSTRAINT "ledger_entries_prompt_id_fkey" FOREIGN KEY (prompt_id) REFERENCES public.content_who_are_they(prompt_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."match_queue"
  ADD CONSTRAINT "match_queue_candidate_user_id_fkey" FOREIGN KEY (candidate_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."match_queue"
  ADD CONSTRAINT "match_queue_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."matches"
  ADD CONSTRAINT "matches_user_high_id_fkey" FOREIGN KEY (user_high_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."matches"
  ADD CONSTRAINT "matches_user_low_id_fkey" FOREIGN KEY (user_low_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."pair_state"
  ADD CONSTRAINT "pair_state_user_high_id_fkey" FOREIGN KEY (user_high_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."pair_state"
  ADD CONSTRAINT "pair_state_user_low_id_fkey" FOREIGN KEY (user_low_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."serious_candidates"
  ADD CONSTRAINT "serious_candidates_candidate_user_id_fkey" FOREIGN KEY (candidate_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."serious_candidates"
  ADD CONSTRAINT "serious_candidates_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_info_vectors"
  ADD CONSTRAINT "user_info_vectors_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."interested_pair_question_answers"
  ADD CONSTRAINT "interested_pair_question_answers_question_owner_fk" FOREIGN KEY (question_id, asked_by_user_id) REFERENCES public.user_match_questions(question_id, user_id)
    ON DELETE CASCADE;

ALTER TABLE "public"."user_photos"
  ADD CONSTRAINT "user_photos_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_preferences"
  ADD CONSTRAINT "user_preferences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_preferred_genders"
  ADD CONSTRAINT "user_preferred_genders_gender_code_fkey" FOREIGN KEY (gender_code) REFERENCES public.genders(code);

ALTER TABLE "public"."user_preferred_genders"
  ADD CONSTRAINT "user_preferred_genders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_preferred_relationship_intents"
  ADD CONSTRAINT "user_preferred_relationship_intents_intent_code_fkey" FOREIGN KEY (intent_code) REFERENCES public.relationship_intents(code);

ALTER TABLE "public"."user_preferred_relationship_intents"
  ADD CONSTRAINT "user_preferred_relationship_intents_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_preferred_religions"
  ADD CONSTRAINT "user_preferred_religions_religion_code_fkey" FOREIGN KEY (religion_code) REFERENCES public.religions(code);

ALTER TABLE "public"."user_preferred_religions"
  ADD CONSTRAINT "user_preferred_religions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_profile"
  ADD CONSTRAINT "user_profile_drinking_status_code_fkey" FOREIGN KEY (drinking_status_code) REFERENCES public.drinking_statuses(code);

ALTER TABLE "public"."user_profile"
  ADD CONSTRAINT "user_profile_gender_code_fkey" FOREIGN KEY (gender_code) REFERENCES public.genders(code);

ALTER TABLE "public"."user_profile"
  ADD CONSTRAINT "user_profile_relationship_intent_code_fkey" FOREIGN KEY (relationship_intent_code) REFERENCES public.relationship_intents(code);

ALTER TABLE "public"."user_profile"
  ADD CONSTRAINT "user_profile_religion_code_fkey" FOREIGN KEY (religion_code) REFERENCES public.religions(code);

ALTER TABLE "public"."user_profile"
  ADD CONSTRAINT "user_profile_smoking_status_code_fkey" FOREIGN KEY (smoking_status_code) REFERENCES public.smoking_statuses(code);

ALTER TABLE "public"."user_profile"
  ADD CONSTRAINT "user_profile_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_profile"
  ADD CONSTRAINT "user_profile_wants_kids_code_fkey" FOREIGN KEY (wants_kids_code) REFERENCES public.kids_preferences(code);

ALTER TABLE "public"."users"
  ADD CONSTRAINT "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."interested_pair_question_answers"
  ADD CONSTRAINT "interested_pair_question_answers_answered_by_user_fk" FOREIGN KEY (answered_by_user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."interested_pair_question_answers"
  ADD CONSTRAINT "interested_pair_question_answers_asked_by_user_fk" FOREIGN KEY (asked_by_user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."interested_pairs"
  ADD CONSTRAINT "interested_pairs_high_user_fk" FOREIGN KEY (user_high_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."interested_pairs"
  ADD CONSTRAINT "interested_pairs_low_user_fk" FOREIGN KEY (user_low_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."ledger_entries"
  ADD CONSTRAINT "ledger_entries_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."serious_candidates"
  ADD CONSTRAINT "serious_candidates_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_computed"
  ADD CONSTRAINT "user_computed_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_info_vectors"
  ADD CONSTRAINT "user_info_vectors_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_match_questions"
  ADD CONSTRAINT "user_match_questions_user_fk" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."user_preferences"
  ADD CONSTRAINT "user_preferences_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_preferred_genders"
  ADD CONSTRAINT "user_preferred_genders_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_preferred_relationship_intents"
  ADD CONSTRAINT "user_preferred_relationship_intents_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_preferred_religions"
  ADD CONSTRAINT "user_preferred_religions_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."user_profile"
  ADD CONSTRAINT "user_profile_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX gated_matches_candidate_idx ON public.hard_gated_candidates USING btree (candidate_user_id);

CREATE INDEX gated_matches_expires_idx ON public.hard_gated_candidates USING btree (expires_at);

CREATE INDEX gated_matches_user_consumed_idx ON public.hard_gated_candidates USING btree (user_id, consumed);

CREATE INDEX gated_matches_user_generated_idx ON public.hard_gated_candidates USING btree (user_id, generated_at);

CREATE INDEX interested_pair_question_answers_answered_by_idx ON public.interested_pair_question_answers USING btree (answered_by_user_id);

CREATE INDEX interested_pair_question_answers_asked_by_idx ON public.interested_pair_question_answers USING btree (asked_by_user_id);

CREATE INDEX interested_pair_question_answers_pair_idx ON public.interested_pair_question_answers USING btree (user_low_id, user_high_id);

CREATE INDEX interested_pairs_high_user_idx ON public.interested_pairs USING btree (user_high_id);

CREATE INDEX interested_pairs_low_user_idx ON public.interested_pairs USING btree (user_low_id);

CREATE INDEX interested_pairs_state_idx ON public.interested_pairs USING btree (state);

CREATE INDEX match_queue_candidate_idx ON public.match_queue USING btree (candidate_user_id);

CREATE INDEX match_queue_expires_at_idx ON public.match_queue USING btree (expires_at);

CREATE INDEX match_queue_user_created_idx ON public.match_queue USING btree (user_id, created_at);

CREATE INDEX match_queue_user_status_position_idx ON public.match_queue USING btree (user_id, status, "position");

CREATE INDEX matches_high_idx ON public.matches USING btree (user_high_id);

CREATE INDEX matches_low_idx ON public.matches USING btree (user_low_id);

CREATE INDEX matches_matched_at_idx ON public.matches USING btree (matched_at);

CREATE INDEX pair_state_high_decision_idx ON public.pair_state USING btree (high_decision);

CREATE INDEX pair_state_high_idx ON public.pair_state USING btree (user_high_id);

CREATE INDEX pair_state_high_state_idx ON public.pair_state USING btree (user_high_id, state);

CREATE INDEX pair_state_low_decision_idx ON public.pair_state USING btree (low_decision);

CREATE INDEX pair_state_low_idx ON public.pair_state USING btree (user_low_id);

CREATE INDEX pair_state_low_state_idx ON public.pair_state USING btree (user_low_id, state);

CREATE INDEX pair_state_state_idx ON public.pair_state USING btree (state);

CREATE INDEX serious_candidates_candidate_idx ON public.serious_candidates USING btree (candidate_user_id);

CREATE INDEX serious_candidates_expires_idx ON public.serious_candidates USING btree (expires_at);

CREATE INDEX serious_candidates_user_score_idx ON public.serious_candidates USING btree (user_id, score DESC);

CREATE INDEX serious_candidates_user_status_position_idx ON public.serious_candidates USING btree (user_id, status, "position");

CREATE INDEX user_match_questions_active_user_idx ON public.user_match_questions USING btree (user_id, is_active, "position");

CREATE INDEX user_match_questions_user_idx ON public.user_match_questions USING btree (user_id);

CREATE UNIQUE INDEX user_photos_one_primary_per_user_idx ON public.user_photos USING btree (user_id)
  WHERE (is_primary = true);

CREATE INDEX user_photos_user_id_idx ON public.user_photos USING btree (user_id);

CREATE INDEX user_preferences_max_age_idx ON public.user_preferences USING btree (max_age);

CREATE INDEX user_preferences_max_distance_idx ON public.user_preferences USING btree (max_distance_km);

CREATE INDEX user_preferences_max_height_idx ON public.user_preferences USING btree (max_height_cm);

CREATE INDEX user_preferences_min_age_idx ON public.user_preferences USING btree (min_age);

CREATE INDEX user_preferences_min_height_idx ON public.user_preferences USING btree (min_height_cm);

CREATE INDEX user_preferred_genders_gender_idx ON public.user_preferred_genders USING btree (gender_code);

CREATE INDEX user_preferred_relationship_intents_intent_idx ON public.user_preferred_relationship_intents USING btree (intent_code);

CREATE INDEX user_preferred_religions_religion_idx ON public.user_preferred_religions USING btree (religion_code);

CREATE INDEX user_profile_city_idx ON public.user_profile USING btree (city);

CREATE INDEX user_profile_dob_idx ON public.user_profile USING btree (date_of_birth);

CREATE INDEX user_profile_gender_idx ON public.user_profile USING btree (gender_code);

CREATE INDEX user_profile_height_idx ON public.user_profile USING btree (height_cm);

CREATE INDEX user_profile_relationship_intent_idx ON public.user_profile USING btree (relationship_intent_code);

CREATE INDEX user_profile_religion_idx ON public.user_profile USING btree (religion_code);

CREATE TRIGGER gated_matches_set_updated_at
  BEFORE UPDATE ON public.hard_gated_candidates
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER interested_pair_question_answers_set_updated_at
  BEFORE UPDATE ON public.interested_pair_question_answers
  FOR EACH ROW
  EXECUTE FUNCTION public.set_interested_pair_question_answers_updated_at();

CREATE TRIGGER interested_pairs_set_updated_at
  BEFORE UPDATE ON public.interested_pairs
  FOR EACH ROW
  EXECUTE FUNCTION public.set_interested_pairs_updated_at();

CREATE TRIGGER pair_state_set_updated_at
  BEFORE UPDATE ON public.pair_state
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER user_info_vectors_set_updated_at
  BEFORE UPDATE ON public.user_info_vectors
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER user_match_questions_set_updated_at
  BEFORE UPDATE ON public.user_match_questions
  FOR EACH ROW
  EXECUTE FUNCTION public.set_user_match_questions_updated_at();

CREATE TRIGGER user_preferences_set_updated_at
  BEFORE UPDATE ON public.user_preferences
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER user_profile_set_updated_at
  BEFORE UPDATE ON public.user_profile
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE POLICY "user_computed_delete_none" ON "public"."user_computed"
  FOR DELETE
  TO "authenticated"
  USING (false);

CREATE POLICY "user_computed_insert_none" ON "public"."user_computed"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (false);

CREATE POLICY "user_computed_select_own" ON "public"."user_computed"
  FOR SELECT
  TO "authenticated"
  USING ((user_id = auth.uid()));

CREATE POLICY "user_computed_update_none" ON "public"."user_computed"
  FOR UPDATE
  TO "authenticated"
  USING (false);

CREATE POLICY "users_delete_none" ON "public"."users"
  FOR DELETE
  TO "authenticated"
  USING (false);

CREATE POLICY "users_insert_own" ON "public"."users"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((id = auth.uid()));

CREATE POLICY "users_select_public" ON "public"."users"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "users_update_own" ON "public"."users"
  FOR UPDATE
  TO "authenticated"
  USING ((id = auth.uid()))
  WITH CHECK ((id = auth.uid()));

COMMENT ON COLUMN "public"."content_who_are_they"."detail" IS 'information about what the prompt says about the person if they reacted me';

GRANT EXECUTE
  ON FUNCTION "public"."distance_km"(double precision, double precision, double precision, double precision)
  TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."refill_gated_matches_for_user"(uuid, integer) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."set_interested_pair_question_answers_updated_at"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."set_interested_pairs_updated_at"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."set_updated_at"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."set_user_match_questions_updated_at"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."ledger_entries_id_seq" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."anchor_types" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."content_who_are_they" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."drinking_statuses" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE
  ON TABLE "public"."embedded_content_who_are_they"
  TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."genders" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."hard_gated_candidates" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE
  ON TABLE "public"."interested_pair_question_answers"
  TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."interested_pairs" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."kids_preferences" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."ledger_entries" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."match_queue" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."matches" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."pair_state" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."relationship_intents" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."religions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."serious_candidates" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."smoking_statuses" TO "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON TABLE "public"."user_computed" FROM "authenticated";

GRANT SELECT ON TABLE "public"."user_computed" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_computed" TO "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_info_vectors" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_match_questions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_photos" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_preferences" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_preferred_genders" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE
  ON TABLE "public"."user_preferred_relationship_intents"
  TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_preferred_religions" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user_profile" TO "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ("birth_date") ON TABLE "public"."users" FROM "authenticated";

GRANT INSERT ("birth_date"), UPDATE ("birth_date") ON TABLE "public"."users" TO "authenticated";

REVOKE ALL ("display_name") ON TABLE "public"."users" FROM "authenticated";

GRANT INSERT ("display_name"), UPDATE ("display_name") ON TABLE "public"."users" TO "authenticated";

REVOKE ALL ("id") ON TABLE "public"."users" FROM "authenticated";

GRANT INSERT ("id") ON TABLE "public"."users" TO "authenticated";

REVOKE ALL ("last_seen_at") ON TABLE "public"."users" FROM "authenticated";

GRANT UPDATE ("last_seen_at") ON TABLE "public"."users" TO "authenticated";

REVOKE ALL ("location_text") ON TABLE "public"."users" FROM "authenticated";

GRANT INSERT ("location_text"), UPDATE ("location_text") ON TABLE "public"."users" TO "authenticated";

REVOKE ALL ON TABLE "public"."users" FROM "authenticated";

GRANT SELECT ON TABLE "public"."users" TO "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "postgres", "service_role";

